### ISSUE TITLE
Exemplo de integração de tesouraria em dcumentos de recibo e fatura-recibo

### ISSUE THREAD

**Issue by albertosilva** [Eticadata/Eticadata.Cust.V17Samples#1]
### Qual o exemplo que gostaria de ter disponivel neste repósitório?
Descriminação de meios de pagamento (tesouraria) utilizados no recebimento de um Recibo ou de uma Fatura-Recibo

### Faça-nos uma pequena descrição funcional do exemplo
Regularização de uma fatura pendente via recibo e emissão de uma Fatura-Recibo, em que o cliente utiliza dois meios de pagamento, ex. numerário e um cheque pré-datado

### Em que tecnologia gostaria de obter o exemplo? (ambiente desktop ou web)
Indiferente

**Comment by alfredo-aguiar-eticadata** [comment]
Exemplo disponibilizado no SalesTAController.
