### ISSUE TITLE
Exemplo de integração de movimentos de stocks com lotes

### ISSUE THREAD

**Issue by albertosilva** [Eticadata/Eticadata.Cust.V17Samples#2]
### Qual o exemplo que gostaria de ter disponivel neste repósitório?
Receção de fornecedor de mercadoria com lotes, incluindo data de validade

### Faça-nos uma pequena descrição funcional do exemplo
O objetivo é perceber se é responsabilidade da aplicação que integra com o ERP verificar se o lote a movimentar já existe ou não, e se não existindo deve criá-lo previamente, ou se o ERP o pode fazer automaticamente.

### Em que tecnologia gostaria de obter o exemplo? (ambiente desktop ou web)
Indiferente, acho que seria importante que no exemplo fosse explicado o significado dos vários parâmetros passados ao método "AlteraLote" nas suas diferentes implementações (documentos de compra, venda e stocks)

**Comment by alfredo-aguiar-eticadata** [comment]
Exemplo disponibilizado no PurchasesController

**Comment by albertosilva** [comment]
Muito obrigado, já confirmámos que o exemplo funcionou.
