### ISSUE TITLE
eMobile

### ISSUE THREAD

**Issue by sergio-sarabando** [Eticadata/Eticadata.Cust.V17Samples#3]
### Qual o exemplo que gostaria de ter disponivel neste repósitório?
Exemplo de aplicação para eMobile
### Faça-nos uma pequena descrição funcional do exemplo
aplicação esqueleto 
### Em que tecnologia gostaria de obter o exemplo? (ambiente desktop ou web)
Mobile

**Comment by alfredo-aguiar-eticadata** [comment]
Estimado @sergio-sarabando, 

O e.Mobile utiliza todos os eventos e/ou regras de validação existentes no ERP, pelo que o processos que são disponibilizados pelo e.Mobile podem ser customizados por essa via.

O objetivo deste repositório é disponibilizar à comunidade de programadores eticadata exemplos de customizações do ERP.

Se o seu propósito é criar uma APP de para smartphones ou tablets deve consultar documentação sobre tecnologias de programação para o efeito como por exemplo: https://www.xamarin.com/ ou https://www.sysdevkalipso.com/en

**Comment by sergio-sarabando** [comment]
Agradeço a resposta, de facto não é o meu propósito obter informação sobre como construir aplicações para smartphotes ou tablets, mas antes como e se podemos usar por exemplo os controles que usam nas vossas aplicações eMobile e ter um esqueleto tal como nas outras tecnologias Web ou Desktop.  

Parecia-lhe enquadrado se alguém lhe pedisse um exemplo para uma aplicação Web, obtivesse uma resposta semelhante. Que se pretendesse desenvolver aplicações Web ou Desktop, poderia consultar diverso material sobre o desenvolvimento de aplicações?

**Comment by alexandremix** [comment]
Eu também gostava de dar um exemplo de como poder utilizar uma ferramenta destas.
Atualmente tenho uma página web que me apresenta os dados do cliente A. Queria saber como poderia ter um FORM para pelo menos alterar a morada dele . Um exemplo simples . Mas tinha que passar pela vossa API. 

tenho uma página chamada cliente.php por exemplo . 
tenho um form nessa página que manda para uma página chamada alteracliente.php

como deveria estar desenhada a página alteracliente.php para enviar dados para a vossa API a pedir para alterar dados do cliente?

Atualmente apenas sei efetuar essa alteração diretamente no SQL. Passando por me logar na BD e correr um insert/update direto , mas isso não passa pela API.

Façam este exemplo simples . que o resto é imitar
